##Excercise 4 - calculate adjusted R2 for mod1
data("airquality")
mod1 = lm(Temp~Ozone, data = airquality)

airquality1 = airquality[which(is.na(airquality$Ozone)==FALSE),]
mod3 = lm(Temp~Ozone, data = airquality1)
res3 = residuals(mod3)
RSS3 = sum(res3^2)
numerator = RSS3/(length(airquality1$Ozone)-2)
denominator = var(airquality1$Temp)
adjustedR2 = 1-(numerator/denominator)
adjustedR2
summary(mod1)
summary(mod3)
##The manually calculated adjustedR2 equals the adjusted R^2 returned from the original model and the model generated by removing the NAs.

##Exercise 5
install.packages('lmtest')
library(lmtest)
plot(residuals(mod1))
dwtest(mod1, alternative=c("two.sided"))
##The plot looks like there is autocorrelation in the residuals, and the dwtest results in a p-value of 7.276e-06, which means there is autocorrelation in the residuals.
##This means the residuals are not independent. 
plot(residuals(mod1)~fitted(mod1))
abline(lm(residuals(mod1)~fitted(mod1)), col="red")
bptest(mod1)
##From the plot, it looks like the residuals are not homoscedastic. However, the bptest results in a p-value of 0.0721, which means we cannot reject the null hypothesis that the residuals are homoscedastic. 
qqnorm(residuals(mod1))
qqline(residuals(mod1), col = "red")
shapiro.test(residuals(mod1))
##The qqplot shows that the residuals deviate from a normal distribution.
##The Shapiro-wilk normality test results in a p-value of 0.000226, so the residuals are not normally distributed.