install.packages("Lahman")
library(Lahman)
data("Salaries")
money14=subset(Salaries,yearID==2014)
hist(money14$salary,main="Distribution of Salary")
avg=mean(money14$salary)
SD=sd(money14$salary)
abline(v=avg,col="blue")
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector=function(times,size,dat,varb){
  a=as.numeric(times)
  b=as.numeric(size)
  v=c()
  for(i in 1:a){
    y=sample(dat[,varb],b,replace=TRUE)
    m=mean(y)
    v=c(v,m)
  }
  v
}

meansVector1=meansVector(10,50,money14,"salary")
hist(meansVector1,probability=TRUE,main="10 subsamples with 50 values each")
lines(density(meansVector1,na.rm=TRUE),col="red")
avg=mean(meansVector1)
SD=sd(meansVector1)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector2=meansVector(20,100,money14,"salary")
hist(meansVector2,probability=TRUE,main="20 subsamples with 100 values each")
lines(density(meansVector2,na.rm=TRUE),col="red")
avg=mean(meansVector2)
SD=sd(meansVector2)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector3=meansVector(40,100,money14,"salary")
hist(meansVector3,probability=TRUE,main="40 subsamples with 100 values each")
lines(density(meansVector3,na.rm=TRUE),col="red")
avg=mean(meansVector3)
SD=sd(meansVector3)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector4=meansVector(80,100,money14,"salary")
hist(meansVector4,probability=TRUE,main="80 subsamples with 100 values each")
lines(density(meansVector4,na.rm=TRUE),col="red")
avg=mean(meansVector4)
SD=sd(meansVector4)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector5=meansVector(160,100,money14,"salary")
hist(meansVector5,probability=TRUE,main="160 subsamples with 100 values each")
lines(density(meansVector5,na.rm=TRUE),col="red")
avg=mean(meansVector5)
SD=sd(meansVector5)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector6=meansVector(320,100,money14,"salary")
hist(meansVector6,probability=TRUE,main="320 subsamples with 100 values each")
lines(density(meansVector6,na.rm=TRUE),col="red")
avg=mean(meansVector6)
SD=sd(meansVector6)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector7=meansVector(640,100,money14,"salary")
hist(meansVector7,probability=TRUE,main="640 subsamples with 100 values each")
lines(density(meansVector7,na.rm=TRUE),col="red")
avg=mean(meansVector7)
SD=sd(meansVector7)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector8=meansVector(1280,100,money14,"salary")
hist(meansVector8,probability=TRUE,main="1280 subsamples with 100 values each")
lines(density(meansVector8,na.rm=TRUE),col="red")
avg=mean(meansVector8)
SD=sd(meansVector8)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector9=meansVector(2560,100,money14,"salary")
hist(meansVector9,probability=TRUE,main="2560 subsamples with 100 values each")
lines(density(meansVector9,na.rm=TRUE),col="red")
avg=mean(meansVector9)
SD=sd(meansVector9)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector10=meansVector(1280,10,money14,"salary")
hist(meansVector10,probability=TRUE,main="1280 subsamples with 10 values each")
lines(density(meansVector10,na.rm=TRUE),col="red")
avg=mean(meansVector10)
SD=sd(meansVector10)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector11=meansVector(1280,20,money14,"salary")
hist(meansVector11,probability=TRUE,main="1280 subsamples with 20 values each")
lines(density(meansVector11,na.rm=TRUE),col="red")
avg=mean(meansVector11)
SD=sd(meansVector11)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector12=meansVector(1280,40,money14,"salary")
hist(meansVector12,probability=TRUE,main="1280 subsamples with 40 values each")
lines(density(meansVector12,na.rm=TRUE),col="red")
avg=mean(meansVector12)
SD=sd(meansVector12)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector13=meansVector(1280,80,money14,"salary")
hist(meansVector13,probability=TRUE,main="1280 subsamples with 80 values each")
lines(density(meansVector13,na.rm=TRUE),col="red")
avg=mean(meansVector13)
SD=sd(meansVector13)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector14=meansVector(1280,160,money14,"salary")
hist(meansVector14,probability=TRUE,main="1280 subsamples with 160 values each")
lines(density(meansVector14,na.rm=TRUE),col="red")
avg=mean(meansVector14)
SD=sd(meansVector14)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector15=meansVector(1280,320,money14,"salary")
hist(meansVector15,probability=TRUE,main="1280 subsamples with 320 values each")
lines(density(meansVector15,na.rm=TRUE),col="red")
avg=mean(meansVector15)
SD=sd(meansVector15)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector16=meansVector(1280,640,money14,"salary")
hist(meansVector16,probability=TRUE,main="1280 subsamples with 640 values each")
lines(density(meansVector16,na.rm=TRUE),col="red")
avg=mean(meansVector16)
SD=sd(meansVector16)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector17=meansVector(1280,1280,money14,"salary")
hist(meansVector17,probability=TRUE,main="1280 subsamples with 1280 values each")
lines(density(meansVector17,na.rm=TRUE),col="red")
avg=mean(meansVector17)
SD=sd(meansVector17)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector18=meansVector(1280,2560,money14,"salary")
hist(meansVector18,probability=TRUE,main="1280 subsamples with 2560 values each")
lines(density(meansVector18,na.rm=TRUE),col="red")
avg=mean(meansVector18)
SD=sd(meansVector18)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))


data("mtcars")
View(mtcars)
hist(mtcars$mpg)
hist(mtcars$mpg,main="distribution of mpg",breaks=10)
avg=mean(mtcars$mpg)
SD=sd(mtcars$mpg)
abline(v=avg,col="blue")
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector=function(times,size,dat,varb){
  a=as.numeric(times)
  b=as.numeric(size)
  v=c()
  for(i in 1:a){
    y=sample(dat[,varb],b,replace=TRUE)
    m=mean(y)
    v=c(v,m)
  }
  v
}

meansVector1=meansVector(10,100,mtcars,"mpg")
hist(meansVector1,probability=TRUE,main="10 subsamples with 100 values each")
lines(density(meansVector1,na.rm=TRUE),col="red")
avg=mean(meansVector1)
SD=sd(meansVector1)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector2=meansVector(20,100,mtcars,"mpg")
hist(meansVector2,probability=TRUE,main="20 subsamples with 100 values each")
lines(density(meansVector2,na.rm=TRUE),col="red")
avg=mean(meansVector2)
SD=sd(meansVector2)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector3=meansVector(40,100,mtcars,"mpg")
hist(meansVector3,probability=TRUE,main="40 subsamples with 100 values each")
lines(density(meansVector3,na.rm=TRUE),col="red")
avg=mean(meansVector3)
SD=sd(meansVector3)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector4=meansVector(80,100,mtcars,"mpg")
hist(meansVector4,probability=TRUE,main="80 subsamples with 100 values each")
lines(density(meansVector4,na.rm=TRUE),col="red")
avg=mean(meansVector4)
SD=sd(meansVector4)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector5=meansVector(160,100,mtcars,"mpg")
hist(meansVector5,probability=TRUE,main="160 subsamples with 100 values each")
lines(density(meansVector5,na.rm=TRUE),col="red")
avg=mean(meansVector5)
SD=sd(meansVector5)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector6=meansVector(320,100,mtcars,"mpg")
hist(meansVector6,probability=TRUE,main="320 subsamples with 100 values each")
lines(density(meansVector6,na.rm=TRUE),col="red")
avg=mean(meansVector6)
SD=sd(meansVector6)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector7=meansVector(640,100,mtcars,"mpg")
hist(meansVector7,probability=TRUE,main="640 subsamples with 100 values each")
lines(density(meansVector7,na.rm=TRUE),col="red")
avg=mean(meansVector7)
SD=sd(meansVector7)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector8=meansVector(1280,100,mtcars,"mpg")
hist(meansVector8,probability=TRUE,main="1280 subsamples with 100 values each")
lines(density(meansVector8,na.rm=TRUE),col="red")
avg=mean(meansVector8)
SD=sd(meansVector8)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector9=meansVector(2560,100,mtcars,"mpg")
hist(meansVector9,probability=TRUE,main="2560 subsamples with 100 values each")
lines(density(meansVector9,na.rm=TRUE),col="red")
avg=mean(meansVector9)
SD=sd(meansVector9)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector10=meansVector(1280,10,mtcars,"mpg")
hist(meansVector10,probability=TRUE,main="1280 subsamples with 10 values each")
lines(density(meansVector10,na.rm=TRUE),col="red")
avg=mean(meansVector10)
SD=sd(meansVector10)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector11=meansVector(1280,20,mtcars,"mpg")
hist(meansVector11,probability=TRUE,main="1280 subsamples with 20 values each")
lines(density(meansVector11,na.rm=TRUE),col="red")
avg=mean(meansVector11)
SD=sd(meansVector11)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector12=meansVector(1280,40,mtcars,"mpg")
hist(meansVector12,probability=TRUE,main="1280 subsamples with 40 values each")
lines(density(meansVector12,na.rm=TRUE),col="red")
avg=mean(meansVector12)
SD=sd(meansVector12)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector13=meansVector(1280,80,mtcars,"mpg")
hist(meansVector13,probability=TRUE,main="1280 subsamples with 80 values each")
lines(density(meansVector13,na.rm=TRUE),col="red")
avg=mean(meansVector13)
SD=sd(meansVector13)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector14=meansVector(1280,160,mtcars,"mpg")
hist(meansVector14,probability=TRUE,main="1280 subsamples with 160 values each")
lines(density(meansVector14,na.rm=TRUE),col="red")
avg=mean(meansVector14)
SD=sd(meansVector14)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector15=meansVector(1280,320,mtcars,"mpg")
hist(meansVector15,probability=TRUE,main="1280 subsamples with 320 values each")
lines(density(meansVector15,na.rm=TRUE),col="red")
avg=mean(meansVector15)
SD=sd(meansVector15)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector16=meansVector(1280,640,mtcars,"mpg")
hist(meansVector16,probability=TRUE,main="1280 subsamples with 640 values each")
lines(density(meansVector16,na.rm=TRUE),col="red")
avg=mean(meansVector16)
SD=sd(meansVector16)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector17=meansVector(1280,1280,mtcars,"mpg")
hist(meansVector17,probability=TRUE,main="1280 subsamples with 1280 values each")
lines(density(meansVector17,na.rm=TRUE),col="red")
avg=mean(meansVector17)
SD=sd(meansVector17)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))

meansVector18=meansVector(1280,2560,mtcars,"mpg")
hist(meansVector18,probability=TRUE,main="1280 subsamples with 2560 values each")
lines(density(meansVector18,na.rm=TRUE),col="red")
avg=mean(meansVector18)
SD=sd(meansVector18)
legend("topright",legend=c(paste0("mean=",avg),paste0("SD=",SD)),text.col=c("blue","dark green"))
