##Excercise One
install.packages("Lahman")
library(Lahman)
data("Salaries")
money14 = subset(Salaries, yearID==2014)

hist(money14$salary, main = "distribution of salary")
avg=mean(money14$salary)
SD=sd(money14$salary)
abline(v=avg, col="blue")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

meansVector = function(times, size, dat, varb){
  a = as.numeric(times)
  b = as.numeric(size)
  v = c()
  for(i in 1:a){
    y = sample(dat[,varb],b,replace=TRUE)
    m = mean(y)
    v = c(v,m)
  }
  v
}
vector1=meansVector(10, 50, money14, "salary")
hist(vector1, freq=FALSE)
lines(density(vector1), col="red")
vector2=meansVector(20, 100, money14, "salary")
hist(vector2, freq=FALSE)
lines(density(vector2), col="red")
vector3=meansVector(40, 100, money14, "salary")
hist(vector3, freq=FALSE)
lines(density(vector3), col="red")
vector4=meansVector(80, 100, money14, "salary")
hist(vector4, freq=FALSE)
lines(density(vector4), col="red")
vector5=meansVector(160, 100, money14, "salary")
hist(vector5, freq=FALSE)
lines(density(vector5), col="red")
vector6=meansVector(320, 100, money14, "salary")
hist(vector6, freq=FALSE)
lines(density(vector6), col="red")
vector7=meansVector(640, 100, money14, "salary")
hist(vector7, freq=FALSE)
lines(density(vector7), col="red")
vector8=meansVector(1280, 100, money14, "salary")
hist(vector8, freq=FALSE)
lines(density(vector8), col="red")
vector9=meansVector(2560, 100, money14, "salary")
hist(vector9, freq=FALSE)
lines(density(vector9), col="red")
vector10=meansVector(2560, 100, money14, "salary")
hist(vector10, freq=FALSE)
lines(density(vector10), col="red")
vector11=meansVector(1280, 10, money14, "salary")
hist(vector11, freq=FALSE)
lines(density(vector11), col="red")
vector12=meansVector(1280, 20, money14, "salary")
hist(vector12, freq=FALSE)
lines(density(vector12), col="red")
vector13=meansVector(1280, 40, money14, "salary")
hist(vector13, freq=FALSE)
lines(density(vector13), col="red")
vector14=meansVector(1280, 80, money14, "salary")
hist(vector14, freq=FALSE)
lines(density(vector14), col="red")
vector15=meansVector(1280, 160, money14, "salary")
hist(vector15, freq=FALSE)
lines(density(vector15), col="red")
vector16=meansVector(1280, 320, money14, "salary")
hist(vector16, freq=FALSE)
lines(density(vector16), col="red")
vector17=meansVector(1280, 640, money14, "salary")
hist(vector17, freq=FALSE)
lines(density(vector17), col="red")
vector18=meansVector(1280, 1280, money14, "salary")
hist(vector18, freq=FALSE)
lines(density(vector18), col="red")
vector19=meansVector(1280, 2560, money14, "salary")
hist(vector19, freq=FALSE)
lines(density(vector19), col="red")

##Excercise 2
data("mtcars")
hist(mtcars$mpg)
hist(mtcars$mpg, main = "distribution of mpg", breaks=10)
avg=mean(mtcars$mpg)
SD=sd(mtcars$mpg)
abline(v=avg, col="blue")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

VectorA=meansVector(10, 20, mtcars, "mpg")
hist(VectorA, freq=FALSE)
VectorB=meansVector(20, 20, mtcars, "mpg")
hist(VectorB, freq=FALSE)
VectorC=meansVector(30, 20, mtcars, "mpg")
hist(VectorC, freq=FALSE)
VectorD=meansVector(40, 20, mtcars, "mpg")
hist(VectorD, freq=FALSE)
VectorE=meansVector(50, 20, mtcars, "mpg")
hist(VectorE, freq=FALSE)

VectorF=meansVector(50, 20, mtcars, "mpg")
hist(VectorF, freq=FALSE)
VectorG=meansVector(50, 30, mtcars, "mpg")
hist(VectorG, freq=FALSE)
VectorH=meansVector(50, 40, mtcars, "mpg")
hist(VectorH, freq=FALSE)
VectorH=meansVector(50, 50, mtcars, "mpg")
hist(VectorH, freq=FALSE)
VectorI=meansVector(50, 60, mtcars, "mpg")
hist(VectorI, freq=FALSE)
