## EXERCISE 1
install.packages("Lahman")
library(Lahman)
data("Salaries")
money14=subset(Salaries,yearID==2014)
head(money14)
hist(money14$salary, main="Distribution of Salary", xlab="2014 Salary")
avg=mean(money14$salary)
SD=sd(money14$salary)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))

meansVector = function(times, size, dat, varb){
  a = as.numeric(times)
  b = as.numeric(size)
  v = c()
  for(i in 1:a){
    y = sample(dat[,varb],b,replace=TRUE)
    m = mean(y)
    v = c(v,m)
  }
  v
}
means=meansVector(10, 50, money14, "salary")
hist(means, freq=FALSE, main="10 Subsamples with 50 Values Each", xlab="Means", ylim=c(0,0.0000015))
avg=mean(means)
SD=sd(means)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means), lwd = 3, col="red")

means1=meansVector(20, 100, money14, "salary")
hist(means1, freq=FALSE, main="20 Subsamples with 100 Values Each", xlab="Means", ylim=c(0,0.0000015))
avg=mean(means1)
SD=sd(means1)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means1), lwd = 3, col="red")

means2=meansVector(40, 100, money14, "salary")
hist(means2, freq=FALSE, main="40 Subsamples with 100 Values Each", xlab="Means", ylim=c(0,0.0000015))
avg=mean(means2)
SD=sd(means2)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means2), lwd = 3, col="red")

means3=meansVector(80, 100, money14, "salary")
hist(means3, freq=FALSE, main="80 Subsamples with 1000 Values Each", xlab="Means", ylim=c(0,0.0000015))
avg=mean(means3)
SD=sd(means3)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means3), lwd = 3, col="red")

means4=meansVector(160, 100, money14, "salary")
hist(means4, freq=FALSE, main="160 Subsamples with 100 Values Each", xlab="Means", ylim=c(0,0.0000015))
avg=mean(means4)
SD=sd(means4)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means4), lwd = 3, col="red")

means5=meansVector(320, 100, money14, "salary")
hist(means5, freq=FALSE, main="320 Subsamples with 100 Values Each", xlab="Means", ylim=c(0,0.0000015))
avg=mean(means5)
SD=sd(means5)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means5), lwd = 3, col="red")

means6=meansVector(640, 100, money14, "salary")
hist(means6, freq=FALSE, main="640 Subsamples with 100 Values Each", xlab="Means", ylim=c(0,0.0000015))
avg=mean(means6)
SD=sd(means6)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means6), lwd = 3, col="red")

means7=meansVector(1280, 100, money14, "salary")
hist(means7, freq=FALSE, main="1280 Subsamples with 100 Values Each", xlab="Means", ylim=c(0,0.0000015))
avg=mean(means7)
SD=sd(means7)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means7), lwd = 3, col="red")

means8=meansVector(2560, 100, money14, "salary")
hist(means8, freq=FALSE, main="2560 Subsamples with 100 Values Each", xlab="Means", ylim=c(0,0.0000015))
avg=mean(means8)
SD=sd(means8)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means8), lwd = 3, col="red")

means9=meansVector(1280, 10, money14, "salary")
hist(means9, freq=FALSE, main="1280 Subsamples with 10 Values Each", xlab="Means", ylim=c(0,0.0000015))
avg=mean(means9)
SD=sd(means9)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means9), lwd = 3, col="red")

means10=meansVector(1280, 20, money14, "salary")
hist(means10, freq=FALSE, main="1280 Subsamples with 20 Values Each", xlab="Means", ylim=c(0,0.0000015))
avg=mean(means10)
SD=sd(means10)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means10), lwd = 3, col="red")

means11=meansVector(1280, 40, money14, "salary")
hist(means11, freq=FALSE, main="1280 Subsamples with 40 Values Each", xlab="Means", ylim=c(0,0.0000015))
avg=mean(means11)
SD=sd(means11)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means11), lwd = 3, col="red")

means12=meansVector(1280, 80, money14, "salary")
hist(means12, freq=FALSE, main="1280 Subsamples with 80 Values Each", xlab="Means", ylim=c(0,0.0000015))
avg=mean(means12)
SD=sd(means12)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means12), lwd = 3, col="red")

means13=meansVector(1280, 160, money14, "salary")
hist(means13, freq=FALSE, main="1280 Subsamples with 160 Values Each", xlab="Means", ylim=c(0,0.0000015))
avg=mean(means13)
SD=sd(means13)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means13), lwd = 3, col="red")

means14=meansVector(1280, 320, money14, "salary")
hist(means14, freq=FALSE, main="1280 Subsamples with 320 Values Each", xlab="Means", ylim=c(0,0.0000015))
avg=mean(means14)
SD=sd(means14)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means14), lwd = 3, col="red")

means15=meansVector(1280, 640, money14, "salary")
hist(means15, freq=FALSE, main="1280 Subsamples with 640 Values Each", xlab="Means", ylim=c(0,0.000002))
avg=mean(means15)
SD=sd(means15)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means15), lwd = 3, col="red")

means16=meansVector(1280, 1280, money14, "salary")
hist(means16, freq=FALSE, main="1280 Subsamples with 1280 Values Each", xlab="Means", ylim=c(0,0.000004))
avg=mean(means16)
SD=sd(means16)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means16), lwd = 3, col="red")

means17=meansVector(1280, 2560, money14, "salary")
hist(means17, freq=FALSE, main="1280 Subsamples with 2560 Values Each", xlab="Means", ylim=c(0,0.000004))
avg=mean(means17)
SD=sd(means17)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means17), lwd = 3, col="red")

## EXERCISE 2
data("mtcars")
hist(mtcars$mpg)
hist(mtcars$mpg, main = "Distribution of mpg", xlab="Miles per gallon", xlim=c(10,40), breaks=10)
avg=mean(mtcars$mpg)
SD=sd(mtcars$mpg)
abline(v=avg, col="blue")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

meansVector = function(times, size, dat, varb){
  a = as.numeric(times)
  b = as.numeric(size)
  v = c()
  for(i in 1:a){
    y = sample(dat[,varb],b,replace=TRUE)
    m = mean(y)
    v = c(v,m)
  }
  v
}
## Histograms w/ gradually increasing number of subsamples but fixed values taken in each subsample
means.a=meansVector(10, 50, mtcars, "mpg")
hist(means.a, main="10 Subsamples with 50 Values Each", xlab="Means", ylim=c(0,5))
avg=mean(means.a)
SD=sd(means.a)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means.a), lwd = 3, col="red")

means.b=meansVector(20, 50, mtcars, "mpg")
hist(means.b, main="20 Subsamples with 50 Values Each", xlab="Means", ylim=c(0,5))
avg=mean(means.b)
SD=sd(means.b)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means.b), lwd = 3, col="red")

means.c=meansVector(40, 50, mtcars, "mpg")
hist(means.c, main="40 Subsamples with 50 Values Each", xlab="Means", ylim=c(0,20))
avg=mean(means.c)
SD=sd(means.c)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means.c), lwd = 3, col="red")

means.d=meansVector(120, 50, mtcars, "mpg")
hist(means.d, main="120 Subsamples with 50 Values Each", xlab="Means", ylim=c(0,30))
avg=mean(means.d)
SD=sd(means.d)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means.d), lwd = 3, col="red")

means.e=meansVector(360, 50, mtcars, "mpg")
hist(means.e, main="360 Subsamples with 50 Values Each", xlab="Means", ylim=c(0,110))
avg=mean(means.e)
SD=sd(means.e)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means.e), lwd = 3, col="red")

## Histograms w/ fixed number of subsamples but gradually increasing values taken in each subsample
means.f=meansVector(400, 100, mtcars, "mpg")
hist(means.f, main="400 Subsamples with 100 Values Each", xlab="Means", ylim=c(0,200))
avg=mean(means.f)
SD=sd(means.f)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means.f), lwd = 3, col="red")

means.g=meansVector(400, 200, mtcars, "mpg")
hist(means.e, main="400 Subsamples with 200 Values Each", xlab="Means", ylim=c(0,200))
avg=mean(means.g)
SD=sd(means.g)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means.g), lwd = 3, col="red")

means.h=meansVector(400, 400, mtcars, "mpg")
hist(means.e, main="400 Subsamples with 400 Values Each", xlab="Means", ylim=c(0,200))
avg=mean(means.h)
SD=sd(means.h)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means.h), lwd = 3, col="red")

means.i=meansVector(400, 1000, mtcars, "mpg")
hist(means.i, main="400 Subsamples with 1000 Values Each", xlab="Means", ylim=c(0,200))
avg=mean(means.i)
SD=sd(means.i)
abline(v=avg, col="blue")
legend("topright", legend=c(paste0("mean=", avg), paste0("SD=", SD)), text.col = c("blue", "dark green"))
lines(density(means.i), lwd = 3, col="red")