### Exercise 1

install.packages("Lahman")
library(Lahman)
data("Salaries")

money14 = subset(Salaries, yearID==2014)
head(money14)

hist(money14$salary, main = "Distribution of Salary", xlab = "Salary")
avg=mean(money14$salary)
SD=sd(money14$salary)
abline(v=avg, col="blue")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

meansVector = function(times, size, dat, varb){
  a = as.numeric(times)
  b = as.numeric(size)
  v = c()
  for(i in 1:a){
    y = sample(dat[,varb],b,replace=TRUE)
    m = mean(y)
    v = c(v,m)
  }
  v
}

means = meansVector(10, 50, money14, "salary")
hist(means, freq = FALSE, main = "10 Subsamples with 50 Values Each", xlab = "Means")
avg=mean(means)
SD=sd(means)
lines(density(means, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means2 = meansVector(20, 100, money14, "salary")
hist(means2, freq = FALSE, main = "20 Subsamples with 100 Values Each", xlab = "Means")
avg=mean(means2)
SD=sd(means2)
lines(density(means2, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means2 = meansVector(20, 100, money14, "salary")
hist(means2, freq = FALSE, main = "20 Subsamples with 100 Values Each", xlab = "Means")
avg=mean(means2)
SD=sd(means2)
lines(density(means2, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means3 = meansVector(40, 100, money14, "salary")
hist(means3, freq = FALSE, main = "40 Subsamples with 100 Values Each", xlab = "Means")
avg=mean(means3)
SD=sd(means3)
lines(density(means3, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means4 = meansVector(80, 100, money14, "salary")
hist(means4, freq = FALSE, main = "80 Subsamples with 100 Values Each", xlab = "Means")
avg=mean(means4)
SD=sd(means4)
lines(density(means4, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means5 = meansVector(160, 100, money14, "salary")
hist(means5, freq = FALSE, main = "160 Subsamples with 100 Values Each", xlab = "Means")
avg=mean(means5)
SD=sd(means5)
lines(density(means5, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means6 = meansVector(320, 100, money14, "salary")
hist(means6, freq = FALSE, main = "320 Subsamples with 100 Values Each", xlab = "Means")
avg=mean(means6)
SD=sd(means6)
lines(density(means6, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means7 = meansVector(640, 100, money14, "salary")
hist(means7, freq = FALSE, main = "640 Subsamples with 100 Values Each", xlab = "Means")
avg=mean(means7)
SD=sd(means7)
lines(density(means7, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means8 = meansVector(1280, 100, money14, "salary")
hist(means8, freq = FALSE, main = "1280 Subsamples with 100 Values Each", xlab = "Means")
avg=mean(means8)
SD=sd(means8)
lines(density(means8, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means9 = meansVector(2560, 100, money14, "salary")
hist(means9, freq = FALSE, main = "2560 Subsamples with 100 Values Each", xlab = "Means")
avg=mean(means9)
SD=sd(means9)
lines(density(means9, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means10 = meansVector(1280, 10, money14, "salary")
hist(means10, freq = FALSE, main = "1280 Subsamples with 10 Values Each", xlab = "Means")
avg=mean(means10)
SD=sd(means10)
lines(density(means10, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means11 = meansVector(1280, 20, money14, "salary")
hist(means11, freq = FALSE, main = "1280 Subsamples with 20 Values Each", xlab = "Means")
avg=mean(means11)
SD=sd(means11)
lines(density(means11, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means12 = meansVector(1280, 40, money14, "salary")
hist(means12, freq = FALSE, main = "1280 Subsamples with 40 Values Each", xlab = "Means")
avg=mean(means12)
SD=sd(means12)
lines(density(means12, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means13 = meansVector(1280, 80, money14, "salary")
hist(means13, freq = FALSE, main = "1280 Subsamples with 80 Values Each", xlab = "Means")
avg=mean(means13)
SD=sd(means13)
lines(density(means13, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means14 = meansVector(1280, 160, money14, "salary")
hist(means14, freq = FALSE, main = "1280 Subsamples with 160 Values Each", xlab = "Means")
avg=mean(means14)
SD=sd(means14)
lines(density(means14, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means15 = meansVector(1280, 320, money14, "salary")
hist(means15, freq = FALSE, main = "1280 Subsamples with 320 Values Each", xlab = "Means")
avg=mean(means15)
SD=sd(means15)
lines(density(means15, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means16 = meansVector(1280, 640, money14, "salary")
hist(means16, freq = FALSE, main = "1280 Subsamples with 640 Values Each", xlab = "Means")
avg=mean(means16)
SD=sd(means16)
lines(density(means16, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means17 = meansVector(1280, 1280, money14, "salary")
hist(means17, freq = FALSE, main = "1280 Subsamples with 1280 Values Each", xlab = "Means")
avg=mean(means17)
SD=sd(means17)
lines(density(means17, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means18 = meansVector(1280, 2560, money14, "salary")
hist(means18, freq = FALSE, main = "1280 Subsamples with 2560 Values Each", xlab = "Means")
avg=mean(means18)
SD=sd(means18)
lines(density(means18, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

### Exercise 2

data("mtcars")
hist(mtcars$mpg)

hist(mtcars$mpg, freq = FALSE, main = "Distribution of mpg", xlab="Means", breaks=9, ylim=c(0, .15), xlim=c(10, 35))
avg=mean(mtcars$mpg)
SD=sd(mtcars$mpg)
lines(density(mtcars$mpg, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

meansVector = function(times, size, dat, varb){
  a = as.numeric(times)
  b = as.numeric(size)
  v = c()
  for(i in 1:a){
    y = sample(dat[,varb],b,replace=TRUE)
    m = mean(y)
    v = c(v,m)
  }
  v
}

means = meansVector(10, 50, mtcars, "mpg")
hist(means, freq = FALSE, main = "10 Subsamples with 50 Values Each", xlab = "Means")
avg=mean(means)
SD=sd(means)
lines(density(means, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means2 = meansVector(20, 100, mtcars, "mpg")
hist(means2, freq = FALSE, main = "20 Subsamples with 100 Values Each", xlab = "Means")
avg=mean(means2)
SD=sd(means2)
lines(density(means2, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means3 = meansVector(40, 100, mtcars, "mpg")
hist(means3, freq = FALSE, main = "40 Subsamples with 100 Values Each", xlab = "Means")
avg=mean(means4)
SD=sd(means4)
lines(density(means4, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means4 = meansVector(80, 100, mtcars, "mpg")
hist(means4, freq = FALSE, main = "80 Subsamples with 100 Values Each", xlab = "Means")
avg=mean(means4)
SD=sd(means4)
lines(density(means4, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means5 = meansVector(160, 100, mtcars, "mpg")
hist(means5, freq = FALSE, main = "160 Subsamples with 100 Values Each", xlab = "Means")
avg=mean(means5)
SD=sd(means5)
lines(density(means5, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means6 = meansVector(320, 100, mtcars, "mpg")
hist(means6, freq = FALSE, main = "320 Subsamples with 100 Values Each", xlab = "Means")
avg=mean(means6)
SD=sd(means6)
lines(density(means6, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means7 = meansVector(640, 100, mtcars, "mpg")
hist(means7, freq = FALSE, main = "640 Subsamples with 100 Values Each", xlab = "Means")
avg=mean(means7)
SD=sd(means7)
lines(density(means7, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means8 = meansVector(1280, 100, mtcars, "mpg")
hist(means8, freq = FALSE, main = "1280 Subsamples with 100 Values Each", xlab = "Means")
avg=mean(means8)
SD=sd(means8)
lines(density(means8, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means9 = meansVector(2560, 100, mtcars, "mpg")
hist(means9, freq = FALSE, main = "2560 Subsamples with 100 Values Each", xlab = "Means")
avg=mean(means9)
SD=sd(means9)
lines(density(means9, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means10 = meansVector(1280, 10, mtcars, "mpg")
hist(means10, freq = FALSE, main = "1280 Subsamples with 10 Values Each", xlab = "Means")
avg=mean(means10)
SD=sd(means10)
lines(density(means10, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means11 = meansVector(1280, 20, mtcars, "mpg")
hist(means11, freq = FALSE, main = "1280 Subsamples with 20 Values Each", xlab = "Means")
avg=mean(means11)
SD=sd(means11)
lines(density(means11, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means12 = meansVector(1280, 40, mtcars, "mpg")
hist(means12, freq = FALSE, main = "1280 Subsamples with 40 Values Each", xlab = "Means")
avg=mean(means12)
SD=sd(means12)
lines(density(means12, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means13 = meansVector(1280, 80, mtcars, "mpg")
hist(means13, freq = FALSE, main = "1280 Subsamples with 80 Values Each", xlab = "Means")
avg=mean(means13)
SD=sd(means13)
lines(density(means13, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means14 = meansVector(1280, 160, mtcars, "mpg")
hist(means14, freq = FALSE, main = "1280 Subsamples with 160 Values Each", xlab = "Means")
avg=mean(means14)
SD=sd(means14)
lines(density(means14, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means15 = meansVector(1280, 320, mtcars, "mpg")
hist(means15, freq = FALSE, main = "1280 Subsamples with 320 Values Each", xlab = "Means")
avg=mean(means15)
SD=sd(means15)
lines(density(means15, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means16 = meansVector(1280, 640, mtcars, "mpg")
hist(means16, freq = FALSE, main = "1280 Subsamples with 640 Values Each", xlab = "Means")
avg=mean(means16)
SD=sd(means16)
lines(density(means16, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means17 = meansVector(1280, 1280, mtcars, "mpg")
hist(means17, freq = FALSE, main = "1280 Subsamples with 1280 Values Each", xlab = "Means")
avg=mean(means17)
SD=sd(means17)
lines(density(means17, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))

means18 = meansVector(1280, 2560, mtcars, "mpg")
hist(means18, freq = FALSE, main = "1280 Subsamples with 2560 Values Each", xlab = "Means")
avg=mean(means18)
SD=sd(means18)
lines(density(means18, na.rm=TRUE), col="red")
legend("topright", legend = c(paste0("mean=", avg), paste0("SD=", SD)),text.col=c("blue", "dark green"))